# Generated by Django 5.0.2 on 2024-02-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='storage',
        ),
    ]
