# Generated by Django 5.0.2 on 2024-03-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_addresses_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
