# Generated by Django 5.0.2 on 2024-03-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_addresses_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='requestcancel',
            field=models.CharField(default='No', max_length=30),
        ),
    ]
