# Generated by Django 5.0.2 on 2024-04-02 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_is_cancelled_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
