# Generated by Django 5.0.2 on 2024-04-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_addresses_created_at_addresses_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='order_total',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
