# Generated by Django 5.0.2 on 2024-04-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_addresses_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='order_total',
        ),
    ]
