# Generated by Django 5.0.2 on 2024-04-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_addresses_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Awaiting payment', 'Awaiting payment'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Returned', 'Returned')], default='New', max_length=20),
        ),
    ]
