# Generated by Django 5.0.2 on 2024-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='requestreturn',
            field=models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=30),
        ),
    ]
