# Generated by Django 5.0.2 on 2024-02-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproducts',
            name='modified_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
