# Generated by Django 5.0.2 on 2024-02-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_myproducts_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproducts',
            name='images',
            field=models.ImageField(upload_to='static/products'),
        ),
    ]
