# Generated by Django 5.0.2 on 2024-02-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_myproducts_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproducts',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
