# Generated by Django 5.0.2 on 2024-03-02 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_variations_images_variations_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variations',
            name='images',
        ),
        migrations.AddField(
            model_name='variations',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.image'),
        ),
    ]
