# Generated by Django 5.0.2 on 2024-03-02 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_variations_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.variations'),
        ),
    ]
