# Generated by Django 5.0.2 on 2024-03-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_image_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
