# Generated by Django 5.0.2 on 2024-03-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_variations_modified_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variations',
            old_name='product',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='myproducts',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='variation_category',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='variation_values',
        ),
        migrations.AddField(
            model_name='myproducts',
            name='brand_name',
            field=models.CharField(default='brand_name', max_length=100),
        ),
        migrations.AddField(
            model_name='variations',
            name='color',
            field=models.CharField(default='color', max_length=100),
        ),
        migrations.AddField(
            model_name='variations',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='variations',
            name='product_name',
            field=models.TextField(default='Variant_product_name', max_length=100),
        ),
        migrations.AddField(
            model_name='variations',
            name='ram',
            field=models.CharField(default='ram', max_length=100),
        ),
        migrations.AddField(
            model_name='variations',
            name='storage',
            field=models.CharField(default='storage', max_length=100),
        ),
        migrations.AlterField(
            model_name='myproducts',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variations',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
