# Generated by Django 5.0.2 on 2024-03-06 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_rename_product_variations_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='variations',
            name='product_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='variations',
            name='ram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='variations',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
