# Generated by Django 5.0.2 on 2024-03-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_myproducts_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproducts',
            name='brand_name',
            field=models.CharField(default='brand_name', max_length=100),
        ),
    ]
