# Generated by Django 5.0.2 on 2024-03-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_myproducts_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='variations',
            name='ram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='variations',
            name='storage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RenameField(
            model_name='variations',
            old_name='product_name',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='variations',
            old_name='brand',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='myproducts',
            name='brand_name',
        ),
        migrations.AddField(
            model_name='myproducts',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Ram',
        ),
        migrations.DeleteModel(
            name='Storage',
        ),
    ]
