# Generated by Django 5.0.2 on 2024-03-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_variations_color_alter_variations_ram_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variations',
            unique_together={('product', 'brand_name', 'color', 'ram', 'storage', 'price', 'stock', 'description')},
        ),
    ]
