# Generated by Django 5.0.2 on 2024-03-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_variations_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variations',
            unique_together={('product', 'brand_name', 'color', 'ram', 'storage', 'price', 'description')},
        ),
    ]
