# Generated by Django 5.0.2 on 2024-04-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_variations_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
