# Generated by Django 5.0.2 on 2024-03-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0005_alter_productoffer_discount_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
