FROM python:3.12-slim
WORKDIR /docker_laptop
RUN apt-get update && apt-get install -y \
    libpq-dev gcc
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]