# Generated by Django 5.0.2 on 2024-02-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_category_my_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_category',
            new_name='Category',
        ),
    ]
