# Generated by Django 5.0.2 on 2024-02-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_category_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/categories'),
        ),
    ]
